apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- 99-secret-github-runners.yaml
- startup-config-map.yaml
- controller-service-account.yaml
- runner-service-account.yaml
- controller-rbac.yaml
- runner-rbac.yaml
- runner-scc.yaml
- statefulset.yaml
# - runner-hpa.yaml  # disabled by default

namespace: github-runners

commonLabels:
  component: github-runner
