apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-d-bench

resources:
  - vllm-default.yaml
  - vllm-experts-parallel.yaml
  - vllm-fp8-cache.yaml
  - vllm-prefix-caching.yaml
  - vllm-prefix-caching-long.yaml
