apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/kueue/releases/download/v0.6.0/manifests.yaml
- ../../base
- cluster-queue.yaml
- multikueue-config.yaml
- admission-check.yaml
- clusters
