apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - manifests/mlflow
# - manifests/github-runners
- manifests/kueue/overlays/management

commonLabels:
  environment: prod

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: mlflow
      namespace: mlflow
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "mlflow.infra.apps.REPLACE_ME.org"
