apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: guidellm-git-clone
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/displayName: "git clone"
    tekton.dev/tags: git
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    Clone a git repository to a workspace. This task clones the repository
    specified by the url parameter into the output workspace.

  params:
    - name: URL
      description: Repository URL to clone
      type: string

    - name: REVISION
      description: Revision to checkout (branch, tag, sha, ref, etc.)
      type: string
      default: "main"

    - name: SUBDIRECTORY
      description: Subdirectory inside the workspace to clone the repo into
      type: string
      default: ""

    - name: DELETE_EXISTING
      description: Clean out the contents of the destination directory if it exists
      type: string
      default: "true"

    - name: VERBOSE
      description: Log the commands that are executed
      type: string
      default: "true"

  workspaces:
    - name: output
      description: The git repo will be cloned onto this workspace

  results:
    - name: COMMIT
      description: The precise commit SHA that was fetched by this Task

    - name: URL
      description: The precise URL that was fetched by this Task

  steps:
    - name: clone
      image: alpine/git:latest
      env:
        - name: HOME
          value: /tmp
        - name: PARAM_URL
          value: $(params.URL)
        - name: PARAM_REVISION
          value: $(params.REVISION)
        - name: PARAM_SUBDIRECTORY
          value: $(params.SUBDIRECTORY)
        - name: PARAM_DELETE_EXISTING
          value: $(params.DELETE_EXISTING)
        - name: PARAM_VERBOSE
          value: $(params.VERBOSE)
        - name: WORKSPACE_OUTPUT_PATH
          value: $(workspaces.output.path)
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "${PARAM_VERBOSE}" = "true" ] ; then
          set -x
        fi

        if [ "${PARAM_DELETE_EXISTING}" = "true" ] ; then
          cleandir() {
            # Delete any existing contents of the repo directory if it exists
            if [ -d "${WORKSPACE_OUTPUT_PATH}/${PARAM_SUBDIRECTORY}" ] ; then
              # Delete non-hidden files and directories
              rm -rf "${WORKSPACE_OUTPUT_PATH}/${PARAM_SUBDIRECTORY}"/*
              # Delete files and directories starting with . but excluding ..
              rm -rf "${WORKSPACE_OUTPUT_PATH}/${PARAM_SUBDIRECTORY}"/.[!.]*
              # Delete files and directories starting with .. plus any other character
              rm -rf "${WORKSPACE_OUTPUT_PATH}/${PARAM_SUBDIRECTORY}"/..?*
            fi
          }

          if [ -z "${PARAM_SUBDIRECTORY}" ]; then
            cleandir
          elif [ -d "${WORKSPACE_OUTPUT_PATH}/${PARAM_SUBDIRECTORY}" ]; then
            cleandir
          fi
        fi

        CHECKOUT_DIR="${WORKSPACE_OUTPUT_PATH}/${PARAM_SUBDIRECTORY}"
        git clone "${PARAM_URL}" "${CHECKOUT_DIR}"
        cd "${CHECKOUT_DIR}"
        git config --global --add safe.directory "${CHECKOUT_DIR}"
        git checkout "${PARAM_REVISION}"

        RESULT_SHA="$(git rev-parse HEAD)"
        EXIT_CODE="$?"

        if [ "${EXIT_CODE}" != 0 ] ; then
          exit "${EXIT_CODE}"
        fi

        printf "%s" "${RESULT_SHA}" > "$(results.COMMIT.path)"
        printf "%s" "${PARAM_URL}" > "$(results.URL.path)"
