apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: redhatai-llama-33-70b-instruct-fp8-dynamic-1k-1k-prefix-
  labels:
    app: llm-d-bench
    pipeline: rhoai-end-to-end-benchmark-prefix-cache
    experiment: redhatai-llama-33-70b-instruct-fp8-dynamic-1k-1k-prefix
    benchmark-tool: guidellm
    deployment-mode: rhoai-prefix-cache
spec:
  pipelineRef:
    # name: rhoai-end-to-end-benchmark-prefix-cache
    name: rhoai-end-to-end-benchmark

  taskRunTemplate:
    serviceAccountName: deploy-model-sa

  ttlSecondsAfterFinished: 3600

  params:
#    - name: SKIP_BENCHMARK
#      value: "true"
#    - name: SKIP_CLEANUP
#      value: "true"

    - name: MODEL_NAME
      value: "RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic"

    # Configuration Profiles
    - name: VLLM_CONFIG
      value: "vllm-prefix-caching"
      # value: "vllm-prefix-caching-long"
    - name: DEPLOYMENT_CONFIG
      value: "deployment-rhoai-kserve"
      # value: "deployment-rhoai-kserve-prefix-cache"
    - name: BENCHMARK_CONFIG
      value: "concurrent-1k-1k"
      # value: "multi-turn"
      # value: "heavy-heterogeneous"

    # Deployment Configuration
    - name: ENABLE_AUTH
      value: "false"
    - name: REPLICAS
      value: "4"
    - name: TP
      value: "2"

    # Precise Prefix Cache Configuration
    - name: BLOCK_SIZE
      value: "64"
    - name: HASH_SEED
      value: "42"
    - name: ZMQ_PORT
      value: "5557"
    - name: SCHEDULER_VERBOSITY
      value: "4"
    - name: ENABLE_CACHE_METRICS
      value: "true"
    - name: CACHE_SCORER_WEIGHT
      value: "2.0"
    - name: LOAD_SCORER_WEIGHT
      value: "1.0"

    # Benchmark Configuration
    - name: ACCELERATOR
      value: "H200"
    - name: BENCHMARK_ENV_VARS
      value:
        - "GUIDELLM__MAX_WORKER_PROCESSES=100"
        # - "MULTITURN=true"

    # MLflow Configuration
    - name: MLFLOW_ENABLED
      value: "true"
    - name: MLFLOW_EXPERIMENT_NAME
      value: "redhatai-llama-33-70b-instruct-fp8-dynamic-1k-1k"
      # value: "redhatai-llama-33-70b-instruct-fp8-dynamic-heavy-heterogeneous"
      # value: "redhatai-llama-33-70b-instruct-fp8-dynamic-multiturn"
    - name: VERSION
      value: "RHOAI-3.3-RC1"
    - name: MLFLOW_TAGS
      value:
        - "deployment=rhoai"
        - "benchmark-tool=guidellm"
        # - "epp=precise-prefix-caching"
        - "epp=prefix-cache-estimation"

  timeouts:
    pipeline: "2h"
    tasks: "2h"

  workspaces:
    - name: models-storage
      persistentVolumeClaim:
        claimName: models-storage

    - name: results
      persistentVolumeClaim:
        claimName: collection-results

    - name: manifests-storage
      emptyDir: {}
