apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-d-bench

resources:
  - concurrent-1k-1k.yaml
  - concurrent-8k-1k.yaml
  - concurrent-8k-1k-pd.yaml
  - heavy-heterogeneous.yaml
  - multi-turn.yaml
