apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: openai-gpt-oss-120b-1k-1k-
  labels:
    app: llm-d-bench
    pipeline: llm-d-end-to-end-benchmark
    experiment: openai-gpt-oss-120b-1k-1k
    benchmark-tool: guidellm
    deployment-mode: precise-prefix-cache
spec:
  pipelineRef:
    name: llm-d-end-to-end-benchmark

  taskRunTemplate:
    serviceAccountName: deploy-model-sa

  ttlSecondsAfterFinished: 3600

  params:
    - name: MODEL_NAME
      value: "openai/gpt-oss-120b"

    - name: VLLM_CONFIG
      value: "vllm-default"
    - name: DEPLOYMENT_CONFIG
      value: "deployment-llm-d-inference-scheduling"
    - name: BENCHMARK_CONFIG
      value: "concurrent-1k-1k"

#    - name: DEPLOYMENT_MODE
#      value: "precise-prefix-cache"
#    - name: LLM_D_REPO_REF
#      value: "afc99a53d44103f552e12deb4f7df8a53fbbabc0"
    - name: MS_IMAGE
      value: "ghcr.io/llm-d/llm-d-cuda:v0.4.0"

    - name: RELEASE_NAME
      value: "openai-gpt-oss-120b"
    - name: REPLICAS
      value: "1"
    - name: TP
      value: "4"

    - name: ACCELERATOR
      value: "H200"
    - name: BENCHMARK_ENV_VARS
      value:
        - "GUIDELLM__MAX_WORKER_PROCESSES=100"

    - name: MLFLOW_ENABLED
      value: "true"
    - name: MLFLOW_EXPERIMENT_NAME
      value: "openai-gpt-oss-120b-1k-1k"
    - name: VERSION
      value: "llm-d-0.4"
      # value: "raw-vllm-0.13.0"
    - name: MLFLOW_TAGS
      value:
        - "deployment=llm-d"
        - "benchmark-tool=guidellm"
        # - "epp=precise-prefix-cache"

#    - name: SKIP_DEPLOY
#      value: "true"
#    - name: SKIP_CLEANUP
#      value: "true"
#    - name: TARGET
#      value: "http://raw-vllm-service.llm-d-bench.svc.cluster.local:8000"

  timeouts:
    pipeline: "2h"
    tasks: "2h"

  workspaces:
    - name: models-storage
      persistentVolumeClaim:
        claimName: models-storage
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    - name: results
      emptyDir: {}
