apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: qwen-25-7b-cache-aware-1k-1k-
  labels:
    app: llm-d-bench
    pipeline: upstream-end-to-end-benchmark
    experiment: qwen-25-7b-cache-aware-1k-1k
    profile: precise-cache
spec:
  pipelineRef:
    name: llm-d-end-to-end-benchmark

  taskRunTemplate:
    serviceAccountName: deploy-model-sa

  ttlSecondsAfterFinished: 3600

  params:
    - name: MODEL_NAME
      value: "Qwen/Qwen2.5-7B-Instruct"

    - name: VLLM_CONFIG
      value: "vllm-default"
    - name: DEPLOYMENT_CONFIG
      value: "deployment-llm-d-inference-scheduling"
    - name: BENCHMARK_CONFIG
      value: "concurrent-1k-1k"

    - name: RELEASE_NAME
      value: "qwen25-7b-cache"
    - name: REPLICAS
      value: "3"
    - name: TP
      value: "1"

    - name: ACCELERATOR
      value: "H200"
    - name: BENCHMARK_ENV_VARS
      value:
        - "GUIDELLM__MAX_WORKER_PROCESSES=100"

    - name: MLFLOW_ENABLED
      value: "true"
    - name: MLFLOW_EXPERIMENT_NAME
      value: "qwen-25-7b-cache-aware-1k-1k"
    - name: VERSION
      value: "RHOAI-3.0"
    - name: MLFLOW_TAGS
      value:
        - "deployment=upstream"
        - "profile=precise-cache"
        - "llm-d-version=RHOAI 3.0"

  timeouts:
    pipeline: "2h"
    tasks: "2h"

  workspaces:
    - name: models-storage
      persistentVolumeClaim:
        claimName: models-storage
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
