apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: redhatai-llama-33-70b-instruct-fp8-dynamic-1k-1k-
  labels:
    app: llm-d-bench
    pipeline: llm-d-end-to-end-benchmark
    experiment: redhatai-llama-33-70b-instruct-fp8-dynamic-1k-1k
    benchmark-tool: guidellm
    deployment-mode: precise-prefix-cache
spec:
  pipelineRef:
    name: llm-d-end-to-end-benchmark

  taskRunTemplate:
    serviceAccountName: deploy-model-sa

  ttlSecondsAfterFinished: 3600

  params:
    - name: MODEL_NAME
      value: "RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic"

    - name: VLLM_CONFIG
      # value: "vllm-prefix-caching-long"
      value: "vllm-prefix-caching"
    - name: DEPLOYMENT_CONFIG
      value: "deployment-llm-d-precise-prefix-cache"
    - name: BENCHMARK_CONFIG
      value: "concurrent-1k-1k"
      # value: "heavy-heterogeneous"
      # value: "multi-turn"

    - name: LLM_D_REPO_REF
      value: "afc99a53d44103f552e12deb4f7df8a53fbbabc0"

    - name: RELEASE_NAME
      value: "redhatai-llama-33-70b-fp8"
    - name: REPLICAS
      value: "4"
    - name: TP
      value: "2"

    - name: ACCELERATOR
      value: "H200"
    - name: BENCHMARK_ENV_VARS
      value:
        - "GUIDELLM__MAX_WORKER_PROCESSES=100"
        # - "MULTITURN=true"

    - name: MLFLOW_ENABLED
      value: "true"
    - name: MLFLOW_EXPERIMENT_NAME
      value: "redhatai-llama-33-70b-instruct-fp8-dynamic-1k-1k"
      # value: "redhatai-llama-33-70b-instruct-fp8-dynamic-heavy-heterogeneous"
      # value: "redhatai-llama-33-70b-instruct-fp8-dynamic-multiturn"
    - name: VERSION
      # value: "llm-d-0.4"
      value: "raw-vllm-0.13.0"
    - name: MLFLOW_TAGS
      value:
        - "deployment=llm-d"
        - "benchmark-tool=guidellm"
        - "epp=none"

    - name: SKIP_DEPLOY
      value: "true"
    - name: SKIP_CLEANUP
      value: "true"
    - name: TARGET
      value: "http://raw-vllm-service.llm-d-bench.svc.cluster.local:8000"

  timeouts:
    pipeline: "2h"
    tasks: "2h"

  workspaces:
    - name: models-storage
      persistentVolumeClaim:
        claimName: models-storage

    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    - name: results
      persistentVolumeClaim:
        claimName: collection-results

    - name: manifests-storage
      emptyDir: {}
