kind: Secret
apiVersion: v1
metadata:
  name: postgresql-secret
  namespace: mlflow
type: Opaque
stringData:
  host: <DB_HOST>
  port: <DB_PORT>
  user: <DB_USER>
  password: <DB_PASSWORD>
  database: <DB_NAME>
---
kind: Secret
apiVersion: v1
metadata:
  name: mlflow-s3-secret
  namespace: mlflow
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "EXPERIMENT_NAMESPACE_REPLACEME"
type: Opaque
stringData:
  access-key: <AWS_ACCESS_KEY_ID>
  secret-key: <AWS_ACCESS_KEY>
  bucket-name: <S3_BUCKET_NAME>
  region: <AWS_REGION>
---
kind: Secret
apiVersion: v1
metadata:
  name: mlflow-ui-auth
  namespace: mlflow
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "EXPERIMENT_NAMESPACE_REPLACEME"
type: Opaque
stringData:
  username: <MLFLOW_USER>
  password: <MLFLOW_PASSWORD>
  flask-secret: <FLASK_SECRET> # for CSRF protection