kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: mlflow

resources:
  - ./namespace.yaml
  - ./99-secret-mlflow.yaml
  - ./rbac.yaml
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml