# Infrastructure (Gateway) Configuration
gateway:
  enabled: true
  gatewayClassName: istio
  service:
    type: ClusterIP
  listeners:
    - name: default
      port: 8000
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRef:
          name: inference-gateway-cert
