apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - namespace.yaml
  - pvc.yaml
  - rbac.yaml
  - grafana-admin-credentials.yaml
  - datasources.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/part-of: llm-d-bench
  app.kubernetes.io/component: monitoring
