{{- if and (eq .Values.upstream false) (eq .Values.downstream true)  }}
{{- $stdName := include "model.serviceName" . }}
{{- $existingService := lookup "serving.kserve.io/v1alpha1" "LLMInferenceService" .Values.namespace $stdName }}
{{- if not $existingService }}
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: {{ $stdName }}
  namespace: {{ .Values.namespace }}
  annotations:
    security.opendatahub.io/enable-auth: "false"
spec:
  model:
    name: {{ .Values.benchmark.model }}
    uri: pvc://models-storage/models/{{ .Values.benchmark.model | replace "/" "-" }}
  replicas: 1  # TODO make Values.replicas
  router:
    route: {}
    gateway: {}
    scheduler: {}
  template:
    containers:
    - name: main
      command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
      args:
        - "--port=8000"
        - "--host=0.0.0.0"
        - "--model=/mnt/models"
        - "--served-model-name={{ .Values.benchmark.model }}"
        - "--tensor-parallel-size={{ .Values.benchmark.tp }}"
        - "--enable-ssl-refresh"
        - "--ssl-certfile=/var/run/kserve/tls/tls.crt"
        - "--ssl-keyfile=/var/run/kserve/tls/tls.key"
      {{- range .Values.benchmark.vllmArgs }}
        - {{ . | quote }}
      {{- end }}
      resources:
        limits:
          nvidia.com/gpu: "{{ .Values.benchmark.gpus | default .Values.benchmark.tp }}"
        requests:
          nvidia.com/gpu: "{{ .Values.benchmark.gpus | default .Values.benchmark.tp }}"
      # for slow startup models
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
          scheme: HTTPS
        initialDelaySeconds: 400
        periodSeconds: 10
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3
{{- end }}
{{- end }}