{{- if and (eq .Values.upstream false) (eq .Values.downstream true) }}
{{- $existingPvc := lookup "v1" "PersistentVolumeClaim" .Values.namespace "models-storage" }}
{{- if not $existingPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-storage
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-provisioner
{{- end }}
{{- end }}